/* dsh-rewind client bundle — generated by scripts/build.mjs from src/client/ */
window.__ModuleLoader__.load({
  id: "dsh-rewind-plugin",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name2 in all)
    __defProp(target, name2, { get: all[name2], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/client/index.ts
var index_exports = {};
__export(index_exports, {
  apply: () => apply,
  inject: () => inject,
  name: () => name
});
module.exports = __toCommonJS(index_exports);

// src/client/hidden.ts
function targetSeqOfArgs(args) {
  if (args === void 0 || args === null) return void 0;
  const match = args.match(/@(\d+)/);
  return match !== null ? Number(match[1]) : void 0;
}
function isExecutedRewindCommand(node, seq) {
  if (node.name !== "rewind" || node.outcome?.kind !== "success") return false;
  if (node.outcome.sourceEventSeq === void 0) return false;
  const args = node.args ?? "";
  return new RegExp(`(?:^|\\s)@${seq}(?:\\s|$)`).test(args);
}
function hasFileImpact(text) {
  if (text === void 0) return true;
  const match = text.match(/impact=(\d+)/);
  if (match !== null) return Number(match[1]) > 0;
  return false;
}
function isPreviewCommand(command) {
  return (command.args ?? "").includes("preview");
}
function isCandidateCommand(command) {
  return (command.args ?? "").includes("__candidates");
}
function hiddenSeqsOf(snap) {
  const hidden = /* @__PURE__ */ new Set();
  const spans = [];
  for (const key of snap.order) {
    const node = snap.nodes.get(key);
    if (node === void 0 || node.kind !== "command") continue;
    const command = node.data;
    if (command.name !== "rewind") continue;
    if (isPreviewCommand(command) || isCandidateCommand(command)) {
      hidden.add(command.seq);
      continue;
    }
    if (command.outcome?.kind !== "success") continue;
    const marker = command.outcome.sourceEventSeq;
    if (marker === void 0) continue;
    hidden.add(command.seq);
    const target = targetSeqOfArgs(command.args);
    if (target !== void 0) {
      spans.push({ start: target, end: marker });
    }
  }
  for (const key of snap.order) {
    const node = snap.nodes.get(key);
    if (node === void 0) continue;
    const anchor = node.anchorSeq;
    if (spans.some((span) => anchor >= span.start && anchor <= span.end)) {
      hidden.add(anchor);
    }
  }
  return hidden;
}

// src/client/candidates.ts
var PREVIEW_CHARS = 80;
var DEFAULT_CANDIDATE_LIMIT = 50;
function messagePreviewOf(message) {
  const text = message.content.map((block) => block.type === "text" && typeof block.text === "string" ? block.text : "").join("").replace(/\s+/g, " ").trim();
  return text.length <= PREVIEW_CHARS ? text : `${text.slice(0, PREVIEW_CHARS - 1)}\u2026`;
}
function formatCandidateTime(time) {
  const d = new Date(time);
  const hh = String(d.getHours()).padStart(2, "0");
  const mm = String(d.getMinutes()).padStart(2, "0");
  return `${hh}:${mm}`;
}
function rewindCandidatesOf(snap, hidden, limit = DEFAULT_CANDIDATE_LIMIT) {
  const candidates = [];
  for (let i = snap.order.length - 1; i >= 0 && candidates.length < limit; i--) {
    const key = snap.order[i];
    if (key === void 0) continue;
    const node = snap.nodes.get(key);
    if (node === void 0 || node.kind !== "user" && node.kind !== "steering") continue;
    if (hidden.has(node.anchorSeq ?? node.data.seq)) continue;
    candidates.push({
      seq: node.data.seq,
      time: node.data.time,
      preview: messagePreviewOf(node.data)
    });
  }
  return candidates;
}
function rewindCandidatesOfChat(snap) {
  return rewindCandidatesOf(snap, hiddenSeqsOf(snap));
}
var CANDIDATE_LIST_HEADER = "candidates=";
function rewindCandidatesFromHostText(text) {
  if (!text.startsWith(CANDIDATE_LIST_HEADER)) return [];
  const lines = text.split("\n").slice(1);
  const candidates = [];
  for (const line of lines) {
    if (line === "") continue;
    const parts = line.split("	");
    if (parts.length !== 3) continue;
    const seq = Number(parts[0]);
    const time = Number(parts[1]);
    const preview = parts[2] ?? "";
    if (!Number.isSafeInteger(seq) || !Number.isFinite(time)) continue;
    candidates.push({ seq, time, preview });
  }
  return candidates;
}
function rewindOptionsFromCandidates(candidates, t) {
  return candidates.map((candidate) => ({
    id: String(candidate.seq),
    label: candidate.preview || t("popover.noText"),
    detail: formatCandidateTime(candidate.time)
  }));
}

// src/client/styles.ts
var CLASS = {
  button: "dsh-rewind-btn",
  popover: "dsh-rewind-popover",
  popoverTitle: "dsh-rewind-popover-title",
  popoverTarget: "dsh-rewind-popover-target",
  popoverOption: "dsh-rewind-popover-option",
  popoverOptionLabel: "dsh-rewind-popover-option-label",
  popoverOptionHint: "dsh-rewind-popover-option-hint",
  popoverImpact: "dsh-rewind-popover-impact",
  popoverActions: "dsh-rewind-popover-actions",
  popoverPrimary: "dsh-rewind-popover-primary",
  popoverGhost: "dsh-rewind-popover-ghost",
  guardHint: "dsh-rewind-guard-hint"
};
var REWIND_ICON_SVG = [
  '<svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">',
  '  <path d="M6.5 2.5 2.5 6.5l4 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>',
  '  <path d="M2.5 6.5h7a4 4 0 0 1 4 4v1.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>',
  "</svg>"
].join("");
var STYLE = `
.dsh-rewind-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  padding: 6px;
  border: none;
  border-radius: 28px;
  background: transparent;
  color: var(--dsw-alias-label-tertiary);
  cursor: pointer;
}
.dsh-rewind-btn:hover {
  background: var(--dsw-alias-interactive-bg-hover);
  color: var(--dsw-alias-label-secondary);
}

.dsh-rewind-popover {
  position: fixed;
  z-index: 1000;
  width: 288px;
  padding: 12px;
  border: 1px solid var(--dsw-alias-border-l2);
  border-radius: 12px;
  background: var(--dsw-specific-menu, var(--dsw-alias-bg-layer-3));
  box-shadow: var(--dsw-shadow-lv3);
  font-size: 14px;
  line-height: 20px;
  color: var(--dsw-alias-label-primary);
}
.dsh-rewind-popover-title {
  font-size: 14px;
  font-weight: 600;
  line-height: 20px;
}
.dsh-rewind-popover-target {
  margin: 4px 0 10px;
  font-size: 12px;
  line-height: 16px;
  color: var(--dsw-alias-label-tertiary);
  word-break: break-all;
}
.dsh-rewind-popover-option {
  display: flex;
  flex-direction: column;
  gap: 2px;
  width: 100%;
  margin: 0 0 6px;
  padding: 8px 10px;
  border: 1px solid transparent;
  border-radius: 8px;
  background: transparent;
  color: inherit;
  font: inherit;
  text-align: left;
  cursor: pointer;
}
.dsh-rewind-popover-option:hover {
  background: var(--dsw-alias-interactive-bg-hover);
}
.dsh-rewind-popover-option:disabled {
  opacity: 0.5;
  cursor: default;
}
.dsh-rewind-popover-option-label {
  font-weight: 500;
}
.dsh-rewind-popover-option-hint {
  font-size: 12px;
  line-height: 16px;
  color: var(--dsw-alias-label-tertiary);
}
.dsh-rewind-popover-impact {
  margin: 4px 0 10px;
  padding: 8px 10px;
  border-radius: 8px;
  background: var(--dsw-alias-interactive-bg-hover);
  font-size: 12px;
  line-height: 16px;
  color: var(--dsw-alias-label-secondary);
  white-space: pre-wrap;
  max-height: 160px;
  overflow: auto;
}
.dsh-rewind-popover-actions {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
}
.dsh-rewind-popover-primary,
.dsh-rewind-popover-ghost {
  padding: 5px 12px;
  border: none;
  border-radius: 8px;
  font: inherit;
  font-size: 13px;
  line-height: 18px;
  cursor: pointer;
}
.dsh-rewind-popover-primary {
  background: var(--dsw-alias-button-primary-fill);
  color: var(--dsw-alias-label-primary-foreground);
}
.dsh-rewind-popover-primary:hover:not(:disabled) {
  background: var(--dsw-alias-button-primary-hover);
}
.dsh-rewind-popover-primary:disabled {
  opacity: 0.5;
  cursor: default;
}
.dsh-rewind-popover-ghost {
  background: transparent;
  color: var(--dsw-alias-label-secondary);
}
.dsh-rewind-popover-ghost:hover {
  background: var(--dsw-alias-interactive-bg-hover);
}

.dsh-rewind-guard-hint {
  position: fixed;
  z-index: 1000;
  max-width: min(440px, calc(100vw - 24px));
  padding: 8px 12px;
  border: 1px solid var(--dsw-alias-border-l2);
  border-radius: 10px;
  background: var(--dsw-specific-menu, var(--dsw-alias-bg-layer-3));
  box-shadow: var(--dsw-shadow-lv3);
  font-size: 13px;
  line-height: 18px;
  color: var(--dsw-alias-label-primary);
  pointer-events: none;
}
`;

// src/client/popover.ts
var popoverEl = null;
var disposeOutside = null;
function closePopover() {
  if (popoverEl !== null) {
    popoverEl.remove();
    popoverEl = null;
  }
  if (disposeOutside !== null) {
    disposeOutside();
    disposeOutside = null;
  }
}
function formatTarget(t, seq, time, preview) {
  const d = new Date(time);
  const hh = String(d.getHours()).padStart(2, "0");
  const mm = String(d.getMinutes()).padStart(2, "0");
  const previewText = preview.length > 0 ? preview : t("popover.noText");
  return `seq ${seq} \xB7 ${hh}:${mm} \xB7 ${previewText}`;
}
function parseImpactList(text) {
  const restores = [];
  const deletes = [];
  for (const line of text.split("\n")) {
    if (line.startsWith("restore:")) restores.push(line.slice("restore:".length));
    else if (line.startsWith("delete:")) deletes.push(line.slice("delete:".length));
  }
  return { restores, deletes };
}
function findCommand(snapshot, match) {
  let found;
  for (const key of snapshot.chat.order) {
    const node = snapshot.chat.nodes.get(key);
    if (node !== void 0 && node.kind === "command") {
      const command = node.data;
      if (match(command)) found = command;
    }
  }
  return found;
}
function knownCommandSeqs(session, match) {
  const known = /* @__PURE__ */ new Set();
  const snapshot = session.getSnapshot();
  for (const key of snapshot.chat.order) {
    const node = snapshot.chat.nodes.get(key);
    if (node !== void 0 && node.kind === "command") {
      const command = node.data;
      if (match(command)) known.add(command.seq);
    }
  }
  return known;
}
function waitForCommand(session, match, timeoutMs = 8e3) {
  return new Promise((resolve) => {
    let settled = false;
    const settle = (value) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      unsubscribe();
      resolve(value);
    };
    const check = () => {
      const node = findCommand(session.getSnapshot(), match);
      if (node?.outcome !== null && node?.outcome !== void 0) {
        settle({ kind: node.outcome.kind, text: node.outcome.text });
      }
    };
    const unsubscribe = session.subscribe(check);
    const timer = setTimeout(() => settle(null), timeoutMs);
    check();
  });
}
function isPreviewFor(node, seq) {
  const args = node.args ?? "";
  return node.name === "rewind" && args.includes("preview") && new RegExp(`(?:^|\\s)@${seq}(?=\\s|$)`).test(args);
}
async function previewImpact(session, seq) {
  const known = knownCommandSeqs(session, (node) => isPreviewFor(node, seq));
  const result = await session.command(`/rewind preview @${seq} both`);
  if (!result.ok || result.value?.matched !== true) return null;
  return waitForCommand(session, (node) => isPreviewFor(node, seq) && !known.has(node.seq));
}
function el(tag, className, text) {
  const node = document.createElement(tag);
  node.className = className;
  if (text !== void 0) node.textContent = text;
  return node;
}
function modeOption(label, hint, onClick) {
  const button = document.createElement("button");
  button.type = "button";
  button.className = CLASS.popoverOption;
  const labelEl = el("span", CLASS.popoverOptionLabel, label);
  const hintEl = el("span", CLASS.popoverOptionHint, hint);
  button.append(labelEl, hintEl);
  button.addEventListener("click", onClick);
  return button;
}
function focusableButtons(root) {
  return Array.from(root.querySelectorAll("button")).filter((button) => !button.disabled && !button.classList.contains(CLASS.popoverGhost));
}
function focusFirst(root) {
  focusableButtons(root)[0]?.focus();
}
function moveFocus(root, dir) {
  const buttons = focusableButtons(root);
  if (buttons.length === 0) return;
  const active = document.activeElement;
  const index = active instanceof HTMLButtonElement ? buttons.indexOf(active) : -1;
  const next = index === -1 ? dir === 1 ? 0 : buttons.length - 1 : (index + dir + buttons.length) % buttons.length;
  buttons[next]?.focus();
}
function renderImpactStep(root, opts, back, cached) {
  const { session, seq, t } = opts;
  const impact = el("div", CLASS.popoverImpact, t("popover.impact.loading"));
  const actions = el("div", CLASS.popoverActions);
  const backButton = document.createElement("button");
  backButton.type = "button";
  backButton.className = CLASS.popoverGhost;
  backButton.textContent = t("popover.back");
  backButton.addEventListener("click", back);
  actions.append(backButton);
  const confirm = document.createElement("button");
  confirm.type = "button";
  confirm.className = CLASS.popoverPrimary;
  confirm.textContent = t("popover.confirm");
  confirm.disabled = true;
  actions.append(confirm);
  root.replaceChildren(impact, actions);
  focusFirst(root);
  void (async () => {
    const outcome = cached ?? await previewImpact(session, seq);
    if (outcome === null) {
      impact.textContent = t("popover.impact.failed", { message: "preview command failed or timed out" });
      return;
    }
    if (outcome.kind === "error") {
      impact.textContent = t("popover.impact.failed", { message: outcome.text ?? "unknown error" });
      return;
    }
    if (outcome.text === void 0) {
      impact.textContent = t("popover.impact.none");
    } else {
      const { restores, deletes } = parseImpactList(outcome.text);
      if (restores.length === 0 && deletes.length === 0) {
        impact.textContent = t("popover.impact.none");
      } else {
        const lines = [
          ...restores.map((path) => t("popover.impact.restore", { path })),
          ...deletes.map((path) => t("popover.impact.delete", { path }))
        ];
        impact.textContent = lines.join("\n");
      }
    }
    confirm.disabled = false;
    confirm.focus();
    confirm.addEventListener("click", () => {
      closePopover();
      opts.onRewind("both");
    });
  })().catch(() => {
    impact.textContent = t("popover.impact.failed", { message: "unexpected error" });
  });
}
function openPopover(opts) {
  closePopover();
  const { session, seq, time, preview, anchor, t } = opts;
  const root = el("div", CLASS.popover);
  root.setAttribute("role", "dialog");
  root.setAttribute("aria-label", t("popover.title"));
  let bothState = { state: "loading" };
  let impactOutcome = null;
  let step = "modes";
  const renderModes = () => {
    step = "modes";
    const children = [
      el("div", CLASS.popoverTitle, t("popover.title")),
      el("div", CLASS.popoverTarget, formatTarget(t, seq, time, preview)),
      modeOption(t("popover.chat"), t("popover.chat.hint"), () => {
        closePopover();
        opts.onRewind("chat");
      })
    ];
    if (bothState.state === "noChanges") {
      children.push(el("div", CLASS.popoverImpact, t("popover.noChanges")));
    } else {
      const option = modeOption(
        t("popover.both"),
        bothState.state === "loading" ? t("popover.checking") : t("popover.both.hint"),
        renderImpact
      );
      if (bothState.state === "loading") option.disabled = true;
      children.push(option);
    }
    const actions = el("div", CLASS.popoverActions);
    const cancel = document.createElement("button");
    cancel.type = "button";
    cancel.className = CLASS.popoverGhost;
    cancel.textContent = t("popover.cancel");
    cancel.addEventListener("click", closePopover);
    actions.append(cancel);
    children.push(actions);
    root.replaceChildren(...children);
    focusFirst(root);
  };
  const renderImpact = () => {
    step = "impact";
    renderImpactStep(root, opts, renderModes, impactOutcome);
  };
  const position = () => {
    const rect = anchor.getBoundingClientRect();
    const gap = 4;
    const height = root.offsetHeight;
    const top = rect.bottom + gap + height <= window.innerHeight - 8 ? rect.bottom + gap : Math.max(8, rect.top - gap - height);
    root.style.top = `${Math.round(top)}px`;
    root.style.left = `${Math.round(Math.min(rect.right, window.innerWidth - 8 - root.offsetWidth))}px`;
  };
  renderModes();
  document.body.append(root);
  position();
  focusFirst(root);
  void (async () => {
    const outcome = await previewImpact(session, seq);
    impactOutcome = outcome;
    if (outcome !== null && outcome.kind === "success") {
      bothState = { state: hasFileImpact(outcome.text) ? "hasChanges" : "noChanges" };
    }
    renderModes();
    position();
  })().catch(() => {
    bothState = { state: "hasChanges" };
    renderModes();
    position();
  });
  popoverEl = root;
  const onPointerDown = (event) => {
    const target = event.target;
    if (root.contains(target) || anchor.contains(target)) return;
    closePopover();
  };
  const onKeyDown = (event) => {
    if (event.key === "ArrowDown") {
      event.preventDefault();
      event.stopPropagation();
      moveFocus(root, 1);
      return;
    }
    if (event.key === "ArrowUp") {
      event.preventDefault();
      event.stopPropagation();
      moveFocus(root, -1);
      return;
    }
    if (event.key === "Escape") {
      event.preventDefault();
      event.stopPropagation();
      if (step === "impact") renderModes();
      else closePopover();
    }
  };
  const deferred = setTimeout(() => {
    document.addEventListener("pointerdown", onPointerDown);
    document.addEventListener("keydown", onKeyDown, true);
  }, 0);
  disposeOutside = () => {
    clearTimeout(deferred);
    document.removeEventListener("pointerdown", onPointerDown);
    document.removeEventListener("keydown", onKeyDown, true);
  };
}

// src/client/portals.tsx
var import_react = require("react");
var import_react_dom = require("react-dom");
var import_jsx_runtime = require("react/jsx-runtime");
function userTextAt(session, seq) {
  const snap = session.getSnapshot();
  for (const key of snap.chat.order) {
    const node = snap.chat.nodes.get(key);
    if (node === void 0 || node.kind !== "user") continue;
    const user = node.data;
    if (user.seq === seq) {
      return user.content.map((block) => block.type === "text" && typeof block.text === "string" ? block.text : "").join("");
    }
  }
  return void 0;
}
function fillComposer(text) {
  const textarea = document.querySelector(COMPOSER_SELECTOR);
  if (textarea === null) return false;
  const setter = Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, "value")?.set;
  setter?.call(textarea, text);
  textarea.dispatchEvent(new Event("input", { bubbles: true }));
  textarea.focus();
  return true;
}
function userNodeOf(session, key) {
  const node = session.getSnapshot().chat.nodes.get(key);
  if (node === void 0 || node.kind !== "user" && node.kind !== "steering") return void 0;
  return node.data;
}
async function runRewindAndFill(session, seq, mode, currentSessionId) {
  const known = knownCommandSeqs(session, (node) => isExecutedRewindCommand(node, seq));
  const result = await session.command(`/rewind @${seq} ${mode}`);
  if (!result.ok || result.value?.matched !== true) return;
  const outcome = await waitForCommand(session, (node) => isExecutedRewindCommand(node, seq) && !known.has(node.seq), 2e4);
  if (outcome === null || outcome.kind !== "success") return;
  if (currentSessionId() !== session.sessionId) return;
  const text = userTextAt(session, seq);
  if (text === void 0 || text === "") return;
  fillComposer(text);
}
var COMPOSER_SELECTOR = "[data-input-scroll] textarea, textarea[data-phase]";
var USER_SEAT_SELECTOR = '[data-chat-flow-kind="user"][data-chat-anchor-key], [data-chat-flow-kind="steering"][data-chat-anchor-key]';
var CHAT_SEAT_SELECTOR = "[data-chat-anchor-key]";
var ACTIONS_ROOT_SELECTOR = "[data-time-hover-root]";
function collectTargets(chat, hiddenSeqs) {
  const rows = /* @__PURE__ */ new Map();
  for (const element of document.querySelectorAll(USER_SEAT_SELECTOR)) {
    const key = element.dataset.chatAnchorKey;
    if (key !== void 0) rows.set(key, element);
  }
  const targets = [];
  for (const key of chat.order) {
    const node = chat.nodes.get(key);
    if (node === void 0 || node.kind !== "user" && node.kind !== "steering") continue;
    const user = node.data;
    if (hiddenSeqs.has(node.anchorSeq ?? user.seq)) continue;
    const row = rows.get(key);
    const messageRoot = row?.querySelector(ACTIONS_ROOT_SELECTOR);
    const actions = messageRoot?.lastElementChild;
    if (!(actions instanceof HTMLElement) || actions.querySelector("button") === null) continue;
    targets.push({ key, container: actions, seq: user.seq, time: user.time, preview: messagePreviewOf(user) });
  }
  return targets;
}
function sameTargets(left, right) {
  return left.length === right.length && left.every((target, index) => {
    const other = right[index];
    return other !== void 0 && target.key === other.key && target.container === other.container && target.seq === other.seq;
  });
}
function RewindPortals({ sessionId, sessionOf, currentSessionId, t, subscribeLocale }) {
  const [targets, setTargets] = (0, import_react.useState)([]);
  const hidden = (0, import_react.useRef)(/* @__PURE__ */ new WeakSet());
  const [, forceRender] = (0, import_react.useReducer)((count) => count + 1, 0);
  (0, import_react.useEffect)(() => subscribeLocale(() => {
    forceRender();
  }), [subscribeLocale]);
  (0, import_react.useLayoutEffect)(() => {
    let active = true;
    let queued = false;
    const refresh = () => {
      if (!active) return;
      const session = sessionOf(sessionId);
      if (session === void 0) {
        setTargets([]);
        return;
      }
      const chat = session.getSnapshot().chat;
      const hiddenSeqs = hiddenSeqsOf(chat);
      let hiddenCount = 0;
      for (const seat of document.querySelectorAll(CHAT_SEAT_SELECTOR)) {
        const key = seat.dataset.chatAnchorKey;
        const anchor = key !== void 0 ? chat.nodes.get(key)?.anchorSeq : void 0;
        if (anchor !== void 0 && hiddenSeqs.has(anchor)) {
          seat.style.display = "none";
          seat.dataset.dshRewindHidden = "true";
          hidden.current.add(seat);
          hiddenCount += 1;
        } else if (hidden.current.has(seat)) {
          seat.style.display = "";
          delete seat.dataset.dshRewindHidden;
          hidden.current.delete(seat);
        }
      }
      if (hiddenSeqs.size > 0 || hiddenCount > 0) {
        console.info(
          `[dsh-rewind] hiding: ${hiddenCount} rows, seqs [${[...hiddenSeqs].slice(0, 20).join(", ")}${hiddenSeqs.size > 20 ? "\u2026" : ""}]`
        );
      }
      const next = collectTargets(chat, hiddenSeqs);
      setTargets((current) => sameTargets(current, next) ? current : next);
    };
    const queueRefresh = () => {
      if (queued || !active) return;
      queued = true;
      queueMicrotask(() => {
        queued = false;
        refresh();
      });
    };
    refresh();
    const observer = new MutationObserver(queueRefresh);
    observer.observe(document.body, { childList: true, subtree: true, attributes: true, attributeFilter: ["style"] });
    return () => {
      active = false;
      observer.disconnect();
    };
  }, [sessionId, sessionOf]);
  return targets.map((target) => (0, import_react_dom.createPortal)(
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
      RewindButton,
      {
        target,
        sessionId,
        sessionOf,
        currentSessionId,
        t
      },
      target.key
    ),
    target.container,
    target.key
  ));
}
function RewindButton({ target, sessionId, sessionOf, currentSessionId, t }) {
  const onClick = (event) => {
    event.stopPropagation();
    const session = sessionOf(sessionId);
    if (session === void 0) {
      console.warn("[dsh-rewind] rewind button clicked with no session binding");
      return;
    }
    const node = userNodeOf(session, target.key);
    if (node === void 0) return;
    openPopover({
      session,
      seq: node.seq,
      time: node.time,
      preview: messagePreviewOf(node),
      anchor: event.currentTarget,
      t,
      onRewind: (mode) => {
        void runRewindAndFill(session, node.seq, mode, currentSessionId);
      }
    });
  };
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
    "button",
    {
      type: "button",
      className: CLASS.button,
      "aria-label": t("button.aria"),
      title: t("button.title"),
      onClick,
      dangerouslySetInnerHTML: { __html: REWIND_ICON_SVG }
    }
  );
}
function createRewindBridge(deps) {
  return function RewindBridge({ sessionId }) {
    return (0, import_react.createElement)(RewindPortals, { sessionId, ...deps });
  };
}

// src/client/locales.ts
var zh = {
  "button.aria": "\u56DE\u9000\u5230\u6B64\u6D88\u606F",
  "button.title": "\u56DE\u9000",
  "popover.title": "\u56DE\u9000\u5230\u8FD9\u6761\u6D88\u606F",
  "popover.noText": "\uFF08\u65E0\u6587\u672C\uFF09",
  "popover.chat": "\u4EC5\u56DE\u9000\u5BF9\u8BDD",
  "popover.chat.hint": "\u53EA\u56DE\u9000\u6A21\u578B\u4E0A\u4E0B\u6587\uFF0C\u4E0D\u52A8\u5DE5\u4F5C\u533A\u6587\u4EF6",
  "popover.both": "\u56DE\u9000\u5BF9\u8BDD\u548C\u4EE3\u7801",
  "popover.both.hint": "\u5BF9\u8BDD\u56DE\u9000\u5E76\u8FD8\u539F\u5DE5\u4F5C\u533A\u6587\u4EF6",
  "popover.checking": "\u6B63\u5728\u68C0\u67E5\u6587\u4EF6\u53D8\u66F4\u2026",
  "popover.noChanges": "\u6B64\u6D88\u606F\u4E4B\u540E\u6CA1\u6709\u53EF\u8FD8\u539F\u7684\u6587\u4EF6\u53D8\u66F4\uFF0C\u4EC5\u53EF\u56DE\u9000\u5BF9\u8BDD",
  "popover.cancel": "\u53D6\u6D88",
  "popover.impact.loading": "\u6B63\u5728\u83B7\u53D6\u5F71\u54CD\u6E05\u5355\u2026",
  "popover.impact.failed": "\u65E0\u6CD5\u83B7\u53D6\u5F71\u54CD\u6E05\u5355\uFF1A{message}",
  "popover.impact.none": "\u76EE\u6807\u4E4B\u540E\u6CA1\u6709\u8DDF\u8E2A\u5230\u7684\u5199\u7C7B\u53D8\u66F4\uFF0C\u65E0\u9700\u8FD8\u539F\u6587\u4EF6\u3002",
  "popover.impact.restore": "\u8FD8\u539F {path}",
  "popover.impact.delete": "\u5220\u9664 {path}",
  "popover.confirm": "\u786E\u8BA4\u56DE\u9000",
  "popover.back": "\u8FD4\u56DE",
  "guard.hint": "/rewind \u624B\u52A8\u8F93\u5165\u4E0D\u63A5\u53D7\u53C2\u6570\uFF0C\u8BF7\u76F4\u63A5\u8F93\u5165 /rewind \u6253\u5F00\u56DE\u9000\u83DC\u5355"
};
var en = {
  "button.aria": "Rewind to this message",
  "button.title": "Rewind",
  "popover.title": "Rewind to this message",
  "popover.noText": "(no text)",
  "popover.chat": "Rewind conversation only",
  "popover.chat.hint": "Cut the model context only; workspace files stay untouched",
  "popover.both": "Rewind conversation and code",
  "popover.both.hint": "Cut the context and restore workspace files",
  "popover.checking": "Checking for file changes\u2026",
  "popover.noChanges": "No tracked file changes after this message; conversation-only rewind",
  "popover.cancel": "Cancel",
  "popover.impact.loading": "Fetching impact list\u2026",
  "popover.impact.failed": "Could not fetch the impact list: {message}",
  "popover.impact.none": "No tracked file changes after the target; nothing to restore.",
  "popover.impact.restore": "Restore {path}",
  "popover.impact.delete": "Delete {path}",
  "popover.confirm": "Confirm rewind",
  "popover.back": "Back",
  "guard.hint": "/rewind takes no typed arguments \u2014 enter /rewind to open the rewind picker."
};

// src/client/index.ts
var name = "dsh-rewind";
var inject = ["slots", "sessions", "locale", "commandUi"];
var NS = "rewind";
var HEADER_ACTIONS_SLOT = "conversation.session.header.actions";
var COMPOSER_SELECTOR2 = "[data-input-scroll] textarea, textarea[data-phase]";
function apply(ctx) {
  ctx.effect(function* () {
    yield ctx.locale.register(NS, { zh, en });
    const t = ctx.locale.bind(NS);
    const style = document.createElement("style");
    style.dataset.plugin = "dsh-rewind";
    style.textContent = STYLE;
    document.head.appendChild(style);
    const sessionOf = (sessionId) => ctx.sessions.binding(sessionId)?.session;
    const currentSessionId = () => ctx.sessions.list.getSnapshot().current;
    const subscribeLocale = (cb) => ctx.locale.subscribe(cb);
    const slots = ctx.slots;
    yield slots.inject(HEADER_ACTIONS_SLOT, () => slots.register(
      {
        name: HEADER_ACTIONS_SLOT,
        // A distinct list-entry id keeps the bridge from shadowing any other
        // header action; the entry renders portals only, never header UI.
        id: "dsh-rewind-portals",
        order: 1e3
      },
      createRewindBridge({ sessionOf, currentSessionId, t, subscribeLocale })
    ));
    const commandUi = ctx.get("commandUi");
    const chatOf = (sessionId) => {
      if (sessionId === void 0) return void 0;
      const face = sessionOf(sessionId);
      return face === void 0 ? void 0 : face.getSnapshot().chat;
    };
    const hasCandidates = (sessionId) => {
      const chat = chatOf(sessionId);
      return chat !== void 0 && rewindCandidatesOfChat(chat).length > 0;
    };
    const fetchHostCandidates = async (face) => {
      const known = knownCommandSeqs(face, (node) => isCandidateCommand(node));
      const result = await face.command("/rewind __candidates");
      if (!result.ok || result.value?.matched !== true) return void 0;
      const outcome = await waitForCommand(face, (node) => isCandidateCommand(node) && !known.has(node.seq));
      if (outcome === null || outcome.kind !== "success" || outcome.text === void 0) return void 0;
      return rewindCandidatesFromHostText(outcome.text);
    };
    const hostCandidatesCache = /* @__PURE__ */ new Map();
    const composerAnchor = () => {
      const textarea = composerTextarea();
      const card = textarea?.closest("[data-composer-card]");
      return card ?? textarea ?? document.body;
    };
    yield commandUi.decorate({
      name: "rewind",
      // The picker exists exactly while the surface has a reachable user
      // message: a fresh session (no candidates) falls through to the host
      // command, which fails with "no user messages" — matching the harness's
      // own decoration convention (see ui-permission-presets).
      available: (session) => hasCandidates(session.sessionId),
      ui: {
        kind: "popupSelect",
        options: async (session) => {
          const face = sessionOf(session.sessionId);
          if (face === void 0) return [];
          const candidates = await fetchHostCandidates(face);
          if (candidates !== void 0) hostCandidatesCache.set(session.sessionId, candidates);
          return candidates === void 0 ? [] : rewindOptionsFromCandidates(candidates, t);
        },
        onSelect: (option, session) => {
          const face = sessionOf(session.sessionId);
          if (face === void 0) return;
          const candidate = hostCandidatesCache.get(session.sessionId)?.find(
            (candidate2) => candidate2.seq === Number(option.id)
          );
          if (candidate === void 0) return;
          openPopover({
            session: face,
            seq: candidate.seq,
            time: candidate.time,
            preview: candidate.preview,
            anchor: composerAnchor(),
            t,
            onRewind: (mode) => {
              void runRewindAndFill(face, candidate.seq, mode, currentSessionId);
            }
          });
        }
      }
    });
    const PARAM_REWIND = /^\s*\/rewind\s+\S+/i;
    const composerTextarea = () => document.querySelector(COMPOSER_SELECTOR2);
    const hasParamRewindDraft = () => {
      const textarea = composerTextarea();
      return textarea !== null && PARAM_REWIND.test(textarea.value);
    };
    let guardHintEl = null;
    let guardHintTimer;
    const showGuardHint = () => {
      if (guardHintEl !== null) guardHintEl.remove();
      if (guardHintTimer !== void 0) window.clearTimeout(guardHintTimer);
      const textarea = composerTextarea();
      if (textarea === null) return;
      const card = textarea.closest("[data-composer-card]");
      const hint = document.createElement("div");
      hint.className = "dsh-rewind-guard-hint";
      hint.setAttribute("role", "status");
      hint.textContent = t("guard.hint");
      document.body.appendChild(hint);
      const rect = card instanceof HTMLElement ? card.getBoundingClientRect() : textarea.getBoundingClientRect();
      hint.style.left = `${Math.round(rect.left)}px`;
      hint.style.bottom = `${Math.round(window.innerHeight - rect.top + 8)}px`;
      guardHintEl = hint;
      guardHintTimer = window.setTimeout(() => {
        hint.remove();
        if (guardHintEl === hint) guardHintEl = null;
        guardHintTimer = void 0;
      }, 3200);
    };
    const onParamRewindSubmit = (event) => {
      if (!hasParamRewindDraft()) return;
      event.preventDefault();
      event.stopPropagation();
      showGuardHint();
    };
    const onKeyDownGuard = (event) => {
      if (event.key !== "Enter" || event.shiftKey || event.isComposing) return;
      onParamRewindSubmit(event);
    };
    const onClickGuard = (event) => {
      if (event.button !== 0 || !hasParamRewindDraft()) return;
      const target = event.target;
      if (!(target instanceof Element)) return;
      const button = target.closest("button");
      if (button === null) return;
      const card = button.closest("[data-composer-card]");
      if (card === null) return;
      const all = card.querySelectorAll("button");
      if (all[all.length - 1] !== button) return;
      if (button.querySelector("rect") !== null) return;
      onParamRewindSubmit(event);
    };
    document.addEventListener("keydown", onKeyDownGuard, true);
    document.addEventListener("click", onClickGuard, true);
    yield () => {
      document.removeEventListener("keydown", onKeyDownGuard, true);
      document.removeEventListener("click", onClickGuard, true);
      if (guardHintEl !== null) guardHintEl.remove();
      if (guardHintTimer !== void 0) window.clearTimeout(guardHintTimer);
      style.remove();
    };
  }, "dsh-rewind client lifecycle");
}

    return module.exports;
  }
});
