// ati-core · 主入口
export * from './linalg.js'
export * from './topology.js'
export * from './optimize.js'
export * from './stats.js'
export * from './operators.js'
export * from './executor.js'
export * from './social.js'
export * from './memory.js'
export * from './planner.js'
export * from './feedback.js'
export * from './conflict.js'
export * from './aci.js'
export { AtiServer } from './server.js'
export { LlmOperator, LlmConfig, socialMessageToLlmInput } from './llm.js'
export { AiSocialBridge } from './ai-social.js'

export const version = '0.7.0'
export const description = 'ATI 分层架构：数学 + 拓扑 + 算子 + 社交 + 接口 + ACI + LLM + AI社交'
