import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import vm from 'node:vm'
function load(extra={}) { let definition;const storage=new Map();vm.runInNewContext(fs.readFileSync(new URL('../client/modules/conversation.js',import.meta.url),'utf8'),{window:{__ModuleLoader__:{load:d=>definition=d}},crypto,console,Response,AbortController,setTimeout,clearTimeout,sessionStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},...extra});return definition.factory(()=>({})) }
const row=(seq,type,data={})=>({event:{seq,type,data}})
const pending={baseSeq:3,request:{sessionId:'s',requestId:'our-request',content:[{type:'text',text:'question'}]}}
const owned=[row(4,'turn/start',{turn:2}),row(6,'user/message',{source:{rpcId:'our-request'}}),row(7,'assistant/message',{message:{content:'answer'}})]
test('prompt acknowledgement is never a completed reply',()=>{const s=load().turnState([],{running:false},pending);assert.equal(s.done,false);assert.equal(s.phase,'waiting')})
test('request association uses native rpcId, not current desktop session or text matching',()=>{const s=load().turnState([row(1,'turn/start',{turn:1}),row(2,'user/message',{source:{rpcId:'other'}}),row(3,'turn/end',{turn:1,reason:{kind:'completed'}})],{running:false},pending);assert.equal(s.done,false)})
test('user event without a turn/start cannot falsely complete',()=>assert.equal(load().turnState([owned[1],row(8,'turn/end',{turn:2,reason:{kind:'completed'}})],{},pending).done,false))
test('matching request and matching turn/end establishes completion',()=>{const s=load().turnState([...owned,row(8,'turn/end',{turn:2,reason:{kind:'completed'}})],{},pending);assert.equal(s.done,true);assert.equal(s.phase,'complete')})
test('unrelated turn/end cannot close the pending request',()=>assert.equal(load().turnState([...owned,row(8,'turn/end',{turn:3,reason:{kind:'completed'}})],{},pending).done,false))
test('native failure exposes actual reason and completes only its own turn',()=>{const s=load().turnState([...owned,row(8,'turn/end',{turn:2,reason:{kind:'error',error:{message:'provider unavailable'}}})],{},pending);assert.equal(s.done,true);assert.equal(s.error,'provider unavailable')})
test('cancelled turn is not represented as successful answer',()=>assert.equal(load().turnState([...owned,row(8,'turn/end',{turn:2,reason:{kind:'cancelled'}})],{},pending).phase,'stopped'))
test('running native session blocks treating older success as current completion',()=>assert.equal(load().turnState([row(8,'turn/end',{turn:2,reason:{kind:'completed'}})],{running:true},null).phase,'running'))
test('outbox is isolated by Session and removal is scoped',()=>{const m=load();m.savePending('s',pending);assert.equal(m.pendingFor('s').request.requestId,'our-request');assert.equal(m.pendingFor('other'),null);m.savePending('s',null);assert.equal(m.pendingFor('s'),null)})
test('malformed or cross-session outbox is ignored',()=>assert.equal(load({sessionStorage:{getItem:()=>JSON.stringify(pending)}}).pendingFor('other'),null))
test('conversation transport rejects destructive and model-changing methods before fetch',async()=>{const m=load({fetch:()=>{throw Error('must not fetch')}});for(const method of ['session/delete','settings/set','tasks/enable','workspaceFiles/write'])await assert.rejects(m.rpcSession(method,{}),/不支持/)})
test('mutation and page requests must have an explicit Session identity',async()=>{const m=load();for(const method of ['session/prompt','session/cancel','session/page','session/create'])await assert.rejects(m.rpcSession(method,{}),/明确/)})
test('native prompt retry preserves the exact request identity and target',async()=>{const calls=[];const m=load({fetch:async(url,o)=>{const body=JSON.parse(o.body);calls.push(body);return new Response(JSON.stringify({rpcId:body.rpcId,result:{ok:true,value:{accepted:true}}}))}});await m.rpcSession('session/prompt',{request:pending.request});await m.rpcSession('session/prompt',{request:pending.request});assert.equal(calls[0].payload.args.request.requestId,calls[1].payload.args.request.requestId);assert.equal(calls[0].payload.args.request.sessionId,'s');assert.notEqual(calls[0].rpcId,calls[1].rpcId)})
test('native explicit rejection is distinguished from ambiguous network failure',async()=>{const m=load({fetch:async(_,o)=>new Response(JSON.stringify({rpcId:JSON.parse(o.body).rpcId,result:{ok:false,error:{message:'rejected'}}}))});await assert.rejects(m.rpcSession('session/prompt',{request:pending.request}),e=>e.definite===true);await assert.rejects(load({fetch:()=>{throw Error('offline')}}).rpcSession('session/prompt',{request:pending.request}),e=>!e.definite)})
test('mismatched RPC response cannot count as acceptance',async()=>await assert.rejects(load({fetch:async()=>new Response(JSON.stringify({rpcId:'wrong',result:{ok:true,value:{accepted:true}}}))}).rpcSession('session/prompt',{request:pending.request}),/无效/))
test('bookmark restores explicit identity and mode without prompting',()=>{const m=load();m.bookmark({id:'s',mode:'conversation'});assert.equal(m.bookmark().id,'s')})
test('conversation build precedes history and no circular history dependency',()=>{const root=new URL('../',import.meta.url),order=fs.readFileSync(new URL('scripts/client-build-meta.mjs',root),'utf8'),source=fs.readFileSync(new URL('client/modules/conversation.js',root),'utf8');assert.ok(order.indexOf("'conversation.js'")<order.indexOf("'history.js'"));assert.doesNotMatch(source,/require\('dsh-open-world\/history'\)/)})

test('visible queued receipt confirms admission before user message exists',()=>assert.equal(load().hasReceipt([row(2,'agent/inbox/spliced',{inserted:[{source:{rpcId:'our-request'}}]})],pending),true))
test('another request receipt cannot clear uncertainty',()=>assert.equal(load().hasReceipt([row(2,'user/message',{source:{rpcId:'other'}})],pending),false))
test('errors before user materialization remain visible without falsely completing',()=>{const r=load().turnState([row(5,'turn/start',{turn:1}),row(6,'turn/end',{turn:1,reason:{kind:'error',error:{message:'runtime startup failed'}}})],{running:false},pending);assert.equal(r.phase,'error');assert.equal(r.done,false);assert.equal(r.error,'runtime startup failed')})
test('uncertain sends are reconciled by reads, not blindly reposted',()=>{const s=fs.readFileSync(new URL('../client/modules/conversation.js',import.meta.url),'utf8');assert.doesNotMatch(s,/send\(true\)|retry =/);assert.match(s,/核对发送状态/);assert.match(s,/确认解除，不重发/)})
test('implicit active-desktop injection is removed from local records',()=>{const s=fs.readFileSync(new URL('../client/modules/chat.js',import.meta.url),'utf8');assert.doesNotMatch(s,/onInject\(text\)/);assert.match(s,/原生问答/)})
