import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import vm from 'node:vm'
function load(extra={}) { let definition;vm.runInNewContext(fs.readFileSync(new URL('../client/modules/history.js',import.meta.url),'utf8'),{window:{__ModuleLoader__:{load:d=>definition=d}},crypto,console,Response,Blob,...extra});return definition.factory(()=>({})) }
const row=(seq,type,data,surfaceOp='append')=>({type:'event',event:{seq,type,data,surfaceOp}})
const call=(seq,id,turn,path)=>row(seq,'tool/call',{callId:id,turn,name:'write',arguments:JSON.stringify({file_path:path,content:'hello'})})
const result=(seq,id,turn,error=false)=>row(seq,'tool/result',{turn,message:{isError:error,source:{callId:id}}})
test('successful mutation records are real sources, not prose mentions',()=>{const m=load();const files=m.collectArtifacts([call(1,'a',1,'a.txt'),result(2,'a',1),row(3,'assistant/message',{message:{content:'imaginary.pdf'}})]);assert.equal(files.length,1);assert.equal(files[0].path,'a.txt')})
test('failed, pending and nonappend mutations contribute no files',()=>{const m=load();assert.equal(m.collectArtifacts([call(1,'a',1,'a'),result(2,'a',1,true),call(3,'b',1,'b'),{...result(4,'b',1),event:{...result(4,'b',1).event,surfaceOp:'replace'}}]).length,0)})
test('call IDs cannot leak across turns',()=>assert.equal(load().collectArtifacts([call(1,'a',1,'secret'),result(2,'a',2)]).length,0))
test('merged history pages are sorted and latest path wins',()=>{const m=load(),f=m.collectArtifacts([result(7,'x',2),call(6,'x',2,'a'),result(2,'y',1),call(1,'y',1,'a')]);assert.equal(f.length,1);assert.equal(f[0].seq,7)})
test('explicit presented paths and labels survive without tool guesses',()=>{const f=load().collectArtifacts([row(3,'deliverables/presented',{files:[{path:'report.html',title:'报告'},{path:'javascript:alert(1)'},null]})]);assert.equal(f.length,1);assert.equal(f[0].name,'报告');assert.equal(f[0].source,'明确交付')})
test('malformed tool arguments and read-only calls are ignored',()=>{const m=load();assert.equal(m.mutationPath({name:'read',arguments:'{"file_path":"x"}'}),null);assert.equal(m.mutationPath({name:'write',arguments:'{bad'}),null);assert.equal(m.mutationPath({name:'str_replace_editor',arguments:{command:'view',path:'x'}}),null)})
test('text messages remain text and keep their role',()=>{const r=load().messageRows([row(1,'user/message',{message:{content:[{type:'text',text:'<script>hi</script>'}]}})]);assert.equal(r[0].text,'<script>hi</script>');assert.equal(r[0].role,'我')})
test('history RPC cannot mutate sessions',async()=>{await assert.rejects(load().rpcRead('session/remove',{}),/仅允许读取/)})
test('missing file service reports an error instead of an empty preview',async()=>{const m=load();m.configureWorkspaceFiles(null);await assert.rejects(m.readArtifact('s',{path:'a.txt'}),/尚未就绪/)})
test('oversized files are rejected before bytes are fetched',async()=>{const m=load();let read=false;m.configureWorkspaceFiles({stat:async()=>({bytes:9000000}),readBytes:async()=>{read=true}});await assert.rejects(m.readArtifact('s',{path:'a.txt'}),/超过/);assert.equal(read,false)})
test('sensitive basenames are not read',async()=>{const m=load();let called=false;m.configureWorkspaceFiles({stat:()=>{called=true}});for(const path of ['.env','D:/private/.env.local','keys/id_rsa','secret.pem'])await assert.rejects(m.readArtifact('s',{path}),/敏感/);assert.equal(called,false)})
test('file reads use the chosen Session and exact original path',async()=>{const m=load();const calls=[];m.configureWorkspaceFiles({stat:async(...a)=>{calls.push(a);return{bytes:2}},readBytes:async(...a)=>{calls.push(a);return{data:new Uint8Array([1,2]),eof:true}}});const r=await m.readArtifact('chosen',{path:'../report.txt'});assert.equal(r.data.byteLength,2);assert.equal(calls[0][0],'chosen');assert.equal(calls[1][1],'../report.txt')})
test('truncated file bytes never become a successful preview',async()=>{const m=load();m.configureWorkspaceFiles({stat:async()=>({bytes:2}),readBytes:async()=>({data:new Uint8Array([1]),eof:false})});await assert.rejects(m.readArtifact('s',{path:'a'}),/完整/)})
test('disposing an old service cannot clear its replacement',async()=>{const m=load(),old=m.configureWorkspaceFiles({}),next={stat:async()=>({bytes:1}),readBytes:async()=>({data:new Uint8Array([1]),eof:true})};m.configureWorkspaceFiles(next);old();assert.equal((await m.readArtifact('s',{path:'a'})).data.byteLength,1)})
test('history is wired into the world and module build order',()=>{const root=new URL('../',import.meta.url),read=p=>fs.readFileSync(new URL(p,root),'utf8');assert.match(read('client/modules/chat.js'),/HistoryBrowser/);assert.match(read('client/modules/history.js'),/workspaceFileScopeId/);const order=read('scripts/client-build-meta.mjs');assert.ok(order.indexOf("'history.js'")<order.indexOf("'chat.js'")&&order.includes("'history.js'"))})
test('native multipart bytes are decoded without corrupting binary data',async()=>{const m=load({fetch:async(url,options)=>{const {rpcId}=JSON.parse(options.body);const fd=new FormData();fd.set('bytes-0',new Blob([new Uint8Array([0,255,10])]));fd.set('metadata',JSON.stringify({rpcId,result:{ok:true,value:{data:null,eof:true}},attachments:[{path:['data'],codec:'bytes',part:'bytes-0'}]}));return new Response(fd)}});const r=await m.rpcRead('workspaceFiles/readBytes',{});assert.deepEqual(Array.from(r.data),[0,255,10])})
test('mismatched RPC identity is rejected',async()=>{const m=load({fetch:async()=>new Response(JSON.stringify({rpcId:'wrong',result:{ok:true,value:{}}}),{headers:{'content-type':'application/json'}})});await assert.rejects(m.rpcRead('session/list',{}),/有效结果/)})
test('unknown file size does not trigger an unbounded read',async()=>{const m=load();let called=false;m.configureWorkspaceFiles({stat:async()=>({}),readBytes:()=>{called=true}});await assert.rejects(m.readArtifact('s',{path:'a'}),/文件大小/);assert.equal(called,false)})
test('directory names cannot introduce traversal or alternate roots',()=>{const m=load();for(const n of ['..','a/b','C:','a\\b'])assert.throws(()=>m.childPath('.',n),/名称无效/);assert.equal(m.childPath('.','report.html'),'report.html');assert.equal(m.childPath('docs','report.html'),'docs/report.html')})
test('history mode pauses local polling and prevents hidden read receipts',()=>{const source=fs.readFileSync(new URL('../client/modules/chat.js',import.meta.url),'utf8');assert.ok(source.includes("if (viewRef.current === 'chat') post(C.CHAT_READ_URL"));assert.ok(source.includes("if (view === 'history') return; load(false)"))})

test('native instruction messages are not mislabelled as user questions',()=>{const rows=load().messageRows([row(1,'user/message',{source:{kind:'runtime-context'},content:'hidden'}),row(2,'user/message',{source:{kind:'user'},content:'visible'})]);assert.equal(rows.length,1);assert.equal(rows[0].text,'visible')})
